### PR TITLE
add ability to see validated cases in app

### LINKED ISSUE #38: Provide ability to show *all* cases in `manage_cases()`
It would be really helpful if `manage_cases()` could get the option to show all cases, not just the ones that have been validated. As things currently stand, it's essentially not possible to look at the cases that pass.

### PR DESCRIPTION
**Pull request by nathancday**
A week later but here is my attempt for a fix #38, ready for critique.

Three points for clarification:
1. I kept your suggestion of using the label 'Validated' (in `input$type`) but wanted to double check because the other case types use the same label as the case class, i.e. switch label to 'Succeeded'

2. I am unsure how to test this and have not written any new tests yet. Happy to build some, just wanted to get feedback first.

3. I put the JS code to disable buttons in www/toggle.js, is that the best location?

### CODE REVIEW

**Comment by lionel-** [comment]
Hi Nathan, sorry for only getting back to you now. This looks like a great start!

It appears to work well for figures that were already validated before starting the Shiny app. Do you think it'd be easy to populate the `Validated` category dynamically, from the newly validated figures?

**Comment by nathancday** [comment]
Adding newly confirmed plots feels doable. I'll take a swing at it and get back.

**Comment by nathancday** [comment]
Hi Lionel, I took a look at this last night and it looks a little more complicated than I thought, but I think there is path forward.

Right now the function `collect_cases()` is called prior to initializing the Shiny app. This sets the list of cases and their status. As cases are validated, `withdraw_cases()` removes the case/cases from the list created by `collect_cases()` and updates file paths so the next time `collect_cases()`/the app is run the cases appear with their new status.

I think if the reactive values object `cases` is modified to be grouped by status instead of the all/active split, then `withdraw_cases()` (or a similar function) could be adjusted to move cases from one status group to another, as opposed to just removing them. That should provide the reactive updating behavior we were after.

Do you think this is reasonable?

**Comment by lionel-** [comment]
This sounds reasonable. Perhaps another way is to maintain two lists of cases, one containing the validated cases and the other the pending cases. Would this be easier?

**Comment by nathancday** [comment]
I think I was making this hard than it needed to be. Re-classing instead of removing cases, seems to work. What's your opinion of doing it like this?

**Comment by lionel-** [comment]
Looks good! My only concern is that validating a case now switches the "Type:" dropdown menu to "Validated". Then you have to go back to "Mismatched" or "New" to continue validating other figures. I think the "Type" selection should not change.

**Comment by nathancday** [comment]
Great, I will make that update.

**Comment by lionel-** [comment]
That's awesome, thanks Nathan! @clauswilke will be happy :)

**Comment by clauswilke** [comment]
Yes, I will!

**Pull request merged**
